export const CHANGE_SİZE="CHANGE_SİZE";
export const GET_SIZE_SUCCESS="GET_SIZE_SUCCESS";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const DOWN_TO_CART="DOWN_TO_CART";